### ISSUE TITLE
Update Graduate student positions page

### ISSUE THREAD

**Issue by chiukenny** [ubc-stat-grad/ubc-stat-grad.github.io#6]
- [x] Move Webmaster to 3rd on list
- [x] Add link for Izzy
- [x] ~~Rename Union Rep to TA Union Rep~~ Add link to CUPE 2278 page to Union Rep title
- [x] Add USS Coordinator with 1-2 positions ~~between Joint Seminar and Fundraiser~~
- [x] Create open postings section near top of page (+ descriptions? To be discussed) and rename current list as filled positions

~~@giankdiluvi thoughts on (?)~~

**Comment by giankdiluvi** [comment]
Okay with 1,2. 

For 3, CUPE is currently bargaining to include RAs and GAAs in their jurisdiction. Might be better to leave it as is (or CUPE 2278 Rep)

For 4, okay with creating posting. What if we put all posting with available positions at the top, or after us three? So like Grad rep, treasurer, webmaster, then USS, fundraiser, union rep?

**Comment by chiukenny** [comment]
3: decided to leave it as-is but add a link to the CUPE 2278 website.

4: agreed. Let's have a separate section of open positions somewhere near the top of the page and the filled positions at the bottom. Might be good to attach brief descriptions with the open positions.

**Comment by nikola-sur** [comment]
@chiukenny @giankdiluvi Done with tasks. Is there a description for the USS Coordinator? What does the job entail?

**Comment by chiukenny** [comment]
@nikola-sur looks good! Description draft for the USS Coordinator position:

> Duties: be the liaison between the SGSA and the USS (Undergraduate Statistics Society) at UBC. Your duties would likely involve being the person of contact for the USS, attending meetings with USS executives as necessary, and organizing/finding volunteers to organize events held in collaboration with the USS. Examples of possible events include a meet-a-grad student session for statistics undergraduates and research/co-op flash talk sessions.

@giankdiluvi feel free to edit thanks.
